### ISSUE TITLE
*BUG* feed_parser_service

### ISSUE THREAD

**Issue by HillviewCap** [HillviewCap/ironmonkey#103]
We need a better way to handle feeds missing the timezone code.
2024-10-11 15:43:08,233 - feed_parser_service - ERROR - Error processing entry https://www.proofpoint.com/us/newsroom/news/us-transportation-and-logistics-firms-targeted-infostealers-backdoors from feed https://www.proofpoint.com/us/rss.xml: type object 'datetime.datetime' has no attribute 'timezone'
Traceback (most recent call last):
  File "/home/leeroyj/ironmonkey/app/services/feed_parser_service.py", line 132, in fetch_and_parse_feed
    parsed_date = parsed_date.replace(tzinfo=datetime.timezone.utc)
                                             ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timezone'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/leeroyj/ironmonkey/app/services/feed_parser_service.py", line 135, in fetch_and_parse_feed
    parsed_date = datetime.now(datetime.timezone.utc)
                               ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timezone'

**Comment by HillviewCap** [comment]
Issue resolved in a previous pr
